---
- name: Sets MongoDB node variables for Cluster
  set_fact:
    alerta_mongod_hosts: '{{ alerta_servers }}'
  when:
    - alerta_mongod_dept | bool

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Install Alerta dependence python package.
  pip:
    name: '{{ item }}'
    state: 'present'
    executable: '/usr/bin/pip3.6'
    extra_args: '--default-timeout=120 -i https://{{ alerta_pypi_url }}/pypi/simple/ --trusted-host {{ alerta_pypi_url }}'
  loop: '{{ alerta_python_dependent_packages }}'
  register: alerta_python_dependent_packages_update
  until: alerta_python_dependent_packages_update is succeeded
  retries: 5
  delay: 2
  notify: Enable alerta service.

- name: Include plugins tasks.
  include: 'plugins.yml'
  when: alerta_plugins is defined

- name: Creating Alerta folder.
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: 'nobody'
    group: 'nobody'
    mode: '0755'
  loop: '{{ alerta_folder }}'

- name: Install Alerta Web UI.
  unarchive:
    src: 'alerta-webui.tar.gz'
    dest: '/data/nginx/site/{{ alerta_ngx_domain }}'
    owner: 'root'
    group: 'root'
    extra_opts: [--strip-components=1]
    validate_certs: 'no'
  environment:
    no_proxy: '*'
  notify: Enable alerta service.

- name: Alerta Configure & Scripts file transfer.
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0664'
  loop: '{{ alerta_conf_scripts }}'
  notify: Enable alerta service.

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Enable Alerta authentication.
  include: 'authentication.yml'
  when: alerta_servers[0] in ansible_default_ipv4.address
