---
- name: Gather Alerta plugins list variables.
  set_fact:
    alerta_plugin_list: "{{ lookup('dict', alerta_plugins, wantlist=True) | json_query('[*].key') }}"

- name: Plugins package file transfer.
  copy:
    src: 'plugins/{{ item }}'
    dest: '/tmp/'
  loop: '{{ alerta_plugin_list }}'

- name: Install Alerta dependence plugins.
  pip:
    name: 'file:///tmp/{{ item }}'
    state: 'present'
    executable: '/usr/bin/pip3.6'
  environment:
    no_proxy: '*'
  loop: "{{ alerta_plugin_list }}"
  notify: Enable alerta service.
