---
- name: Enable alerta service
  systemd:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop:
    - 'alertad.service'
    - 'alerta-webui.service'
  listen: Ensure Alerta service is enabled